
@category = all
@places_id = 22bc0fd1-3619-4232-9c91-acdde16a2ce2
### get places
GET http://127.0.0.1:3333/places/{{category}}

### view places by id
GET  http://127.0.0.1:3333/view/places/{{places_id}}